#!/usr/bin/env node
// Generates tzmap.js (Windows time-zone name → IANA) from the Unicode CLDR
// windowsZones.xml, canonical entry per zone (territory 001). Not shipped; the
// only script that needs the network. Same input → byte-identical output.
//
// Usage: node scripts/gen-tzmap.mjs [path/to/windowsZones.xml]
//   without an argument the table is fetched from the CLDR repository
//   (behind an env proxy: NODE_USE_ENV_PROXY=1).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml';
const out = fileURLToPath(new URL('../tzmap.js', import.meta.url));

const arg = process.argv[2];
const xml = arg ? readFileSync(arg, 'utf8') : await (async () => {
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`${SOURCE}: HTTP ${res.status}`);
  return res.text();
})();

const map = new Map();
for (const m of xml.matchAll(/<mapZone\s+other="([^"]+)"\s+territory="001"\s+type="([^"\s]+)"\s*\/>/g)) {
  if (map.has(m[1])) throw new Error(`duplicate Windows zone ${m[1]}`);
  map.set(m[1], m[2]);
}
if (map.size < 100) throw new Error(`only ${map.size} canonical zones parsed -- the table format changed`);

const keys = [...map.keys()].sort();
const version = (xml.match(/otherVersion="([^"]+)"/) ?? [])[1] ?? 'unknown version';
const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map.get(k))},`).join('\n');
writeFileSync(out, `// Windows time-zone names → IANA, from Unicode CLDR windowsZones.xml
// (territory 001, otherVersion ${version}). Generated by scripts/gen-tzmap.mjs; do not edit.
export const WINDOWS_TZ = Object.freeze({
${body}
});
`);
console.log(`tzmap.js: ${keys.length} zones`);
