#!/usr/bin/env node
// Generates tzmap.js (Windows time-zone name → IANA) from the Unicode CLDR
// windowsZones.xml, canonical entry per zone (territory 001). Not shipped; the
// only script that needs the network. Same input → byte-identical output.
//
// Usage: node scripts/gen-tzmap.mjs [--check] [path/to/windowsZones.xml]
//   without a path the table is fetched from the CLDR release TAG (behind an
//   env proxy: NODE_USE_ENV_PROXY=1); a given file must be that release's.
//   --check compares instead of writing: exit 1 when tzmap.js differs.
//   A new TAG also goes into NOTICE (test/tzmap.test.mjs compares them).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const TAG = 'release-48-2';
const SOURCE = `https://raw.githubusercontent.com/unicode-org/cldr/${TAG}/common/supplemental/windowsZones.xml`;
const out = fileURLToPath(new URL('../tzmap.js', import.meta.url));

const check = process.argv.includes('--check');
const arg = process.argv.slice(2).find((a) => a !== '--check');
const xml = arg ? readFileSync(arg, 'utf8') : await (async () => {
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`${SOURCE}: HTTP ${res.status}`);
  return res.text();
})();

const map = new Map();
for (const m of xml.matchAll(/<mapZone\s+other="([^"]+)"\s+territory="001"\s+type="([^"\s]+)"\s*\/>/g)) {
  if (map.has(m[1])) throw new Error(`duplicate Windows zone ${m[1]}`);
  map.set(m[1], m[2]);
}
const canonical = xml.match(/territory="001"/g)?.length ?? 0;
if (map.size !== canonical || map.size < 100) throw new Error(`${map.size} of ${canonical} canonical zones parsed -- the table format changed`);

const keys = [...map.keys()].sort();
const version = (xml.match(/otherVersion="([^"]+)"/) ?? [])[1] ?? 'unknown version';
const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map.get(k))},`).join('\n');
const text = `// Windows time-zone names → IANA, from Unicode CLDR windowsZones.xml
// (CLDR ${TAG}, territory 001, otherVersion ${version}). Generated by scripts/gen-tzmap.mjs; do not edit.
export const WINDOWS_TZ = Object.freeze({
${body}
});
`;
if (check) {
  const same = readFileSync(out, 'utf8') === text;
  console.log(`tzmap.js ${same ? 'matches' : 'DIFFERS from'} CLDR ${TAG} (${keys.length} zones)`);
  process.exit(same ? 0 : 1);
}
writeFileSync(out, text);
console.log(`tzmap.js: ${keys.length} zones`);
